### PR TITLE
Feat/footer

### PR DESCRIPTION
**Pull request by BastienWinant**
## Footer

Changes have been made to /index.html and /index.css to add a footer section at the bottom of the page.

It's most likely not a final version, but I wanted to provide an update and get some feedback on the implementation.
I've tried to stick to the Figma design closely, but did make some arbitrary decisions with regard to responsiveness (it should be rendering on all viewport widths).

I've left out the social media links for now.

### CODE REVIEW

**Review by michaella23 — APPROVED** [review]
This looks great! Thanks for adding responsiveness as well. I think you're right that this is a feature we may amend in the future. 
I'm going to merge this now, but we _do_ want to have a footer on each page. Maybe we should create a new issue? Get another contributor to add these? Or do you want to create another PR for the same ticket?

**Comment by BastienWinant** [comment]
Thanks for the help and the feedback @michaella23 !

Do you think it makes sense to create a separate issue for adding the footer to each page, but hold off on creating it until we have the final version of the footer? The way I see it, we only need to finalize the links to have the complete footer, which we could do as part of this issue.

**Comment by michaella23** [comment]
@BastienWinant I see your line of thinking and that makes sense to me. I guess I was thinking that eventually we might have an issue to render the Footer with JavaScript instead of hard-coding it in the HTML. (Same with the header...) So we could also fix the links later on down the line.
Do you have an idea about what we would use for the links? Would these be the HTML, CSS, JavaScript and React links? We could link them to free courses on Scrimba maybe? Or link them to other sections of our site...

**Comment by michaella23** [comment]
That sounds good to me @BastienWinant!

**Pull request merged**
