### PR TITLE
added module 3 and 4 to the curriculum page

### PR DESCRIPTION
**Pull request by eram23**

### CODE REVIEW

**Comment by michaella23** [comment]
Hey @eram23, I see that this branch has conflicts that must be resolved. It might be that you hadn't pulled down upstream changes before pushing your new changes. Can you try using `git pull upstream main` in this feature branch? Assuming this brings in some changes, then you will stage (add), commit, and push again. You don't need to create a separate pull request. Just tag me when it's done, and I'll check it out. When you come back to this PR, check to make sure you don't have any conflicts.
Screen Shot 2024-07-12 at 10 15 44 AM

thanks!

**Comment by eram23** [comment]
Hey @michaella23 I just tried to use `git pull upstream main` and it says that my branch is already up to date. After that I tried to go through the process of pushing it again and it gave me this in the terminal: 
`branch 'curriculum-page' set up to track 'origin/curriculum-page'.
Everything up-to-date`

**Comment by michaella23** [comment]
@eram23 thanks for the info... That message makes me think that your the default origin branch was reset to `curriculum-page` rather than `main`... What happens if you do `git pull origin main`?

**Comment by eram23** [comment]
Hi @michaella23 thank you I believe I was able to get my fork up to date with that command. I went ahead and requested another pull request and I believe it does not have any merge conflicts this time..

**Pull request closed without merging**
