### PR TITLE
Read me - links corrected

### PR DESCRIPTION
**Pull request by eram23**
Fixed the link that was not working (code of conduct).

### CODE REVIEW

**Comment by michaella23** [comment]
Oh! Can you also look at line 6 in the README and check if all of those links are working? @eram23

**Comment by eram23** [comment]
Hi @michaella23 I double checked the links and made sure they are correct I just need to sync my changes. 

And will requesting the new changes from main - git pull upstream main  erase any of the progress I have made on my local version?

**Review by michaella23 — APPROVED** [review]
Thanks for making the requested changes @eram23. If you pull changes from upstream, your code won't be overwritten. If there is anything that is conflicting, you'll be prompted to accept incoming changes - which you can check to see if everything looks alright. It might bump code you've written onto a different line or something like that.

**Comment by michaella23** [comment]
This PR is also showing the changes you made to `index.html`. I am going to go ahead and merge, but it can be a good practice to commit and push changes corresponding to an issue in one PR and then commit and push the other changes separately. You may still be working on those issues - #23 and #24... Let me know though!

**Comment by eram23** [comment]
All done with issues #23 and #24 ! Should I go ahead and delete my read-me branch?

**Comment by michaella23** [comment]
You can, yes. @eram23

**Pull request merged**
