### PR TITLE
Addedcsslinktohtmlfiles

### PR DESCRIPTION
**Pull request by othukeodoko**
I added the link the link tag to the html files. 

I think it impacted activities.html, contributors.html and curriculum.html. The boilerplate code for htmlNotes needs to be reviewed and worked on. I felt that was outside the scope of the issue assigned to me.

### CODE REVIEW

**Review by michaella23 — CHANGES_REQUESTED** [review]
Hey @othukeodoko! Thanks for adding these links. Did you test to make sure that changes made in `index.css` would be reflected in these files? You could set the background color for the body for example, since we don't have much content yet.

I agree that adding the link to the new file is out of the scope for this issue, so don't worry about that. But please add a link to the stylesheet in `index.html`.

Once you make the changes you can go through the same flow - add, commit, and finally then push. Comment here and tag me when you have made these changes. You don't need to submit another pull request.

**Comment by othukeodoko** [comment]
@micha thanks for the feedback. I did test by adding an H1 element and setting the color to red and used the open live feature on vs code and it displayed successfully. I will update the index.html also.

**Comment by othukeodoko** [comment]
@michaella23 I have made the changes you requested. Thanks

**Review by michaella23 — APPROVED** [review]
Thank you for this contribution!

**Pull request merged**
