### PR TITLE
Added hover effect on nav links

### PR DESCRIPTION
**Pull request by Diegoireland1975**
added hover effect on links, they will change color and background color, added transition as well"

### CODE REVIEW

**Review by michaella23 — COMMENTED** [review]
@Diegoireland1975 I am seeing some formatting changes in the CSS file, but am not immediately seeing where those hover effects would have been added. Which links were you applying changes to?

**Comment by Diegoireland1975** [comment]
the hover effect is in the links in the nav items, I added a background color and they should change the text color as well

**Comment by michaella23** [comment]
@Diegoireland1975 I have looked a few times through the code that is found in the 'Files Changed' tab, and I don't see a background color, text color or hover effect for any nav items. I'm sorry. Are you sure. you committed and synced all of your changes?
Screenshot 2024-08-10 at 12 19 48 PM

**Comment by Diegoireland1975** [comment]
@michaella23 Hi
Yes I committed the changes.
If it's not showing maybe I did something wrong when I created a pull request.
I will review the code. 
Could I create another pull request?

**Comment by michaella23** [comment]
> Could I create another pull request?
@Diegoireland1975 yes of course! But you may not need to... I think if you stage and commit the new changes, and then sync those changes it will show up on this PR. Take a look and see.

I went and looked at your fork of the project and I see two different commits - one has styles on the nav elements, but the other one removes the styles from those elements

**Comment by Diegoireland1975** [comment]
@michaella23 I tried to push the commit again, now they appear to be in file changed

**Pull request merged**
