### PR TITLE
Addtocontributer

### PR DESCRIPTION
**Pull request by fame372**
added to my info and an image to contributors.js

### CODE REVIEW

**Review by michaella23 — CHANGES_REQUESTED** [review]
I was all set to approve this Pull Request, but it actually has the CODE_OF_CONDUCT.md attached to it. So here's what we need to do:
1. I think that your remote branch still exists. If you type `git branch` in the terminal you'll see it. 
2. Next type `git switch` followed by the name of that branch and hit enter. 
3. While you are in that feature branch, delete the Code of Conduct file.
4. Now go through the process we did before - `git add .`, `git commit -m removed-code-of-conduct`, and finally `git push --set-upstream origin` followed by the name of your branch. 
5. Comment here when you have made that change. You don't need to submit another pull request.

I will review the changes and merge them with our project!

Thank you!

**Comment by michaella23** [comment]
Hey @fame372 , did you have any questions about making these changes? I'd be happy to help!

**Comment by fame372** [comment]
Hi micha I am done with the task please check it out and let me know if I need to make any changes.

**Review by michaella23 — APPROVED** [review]
Thanks @fame372! I'm happy to merge your pull request. 🥳

**Pull request merged**
